version: '3.1'
services: 
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'root12345'
    redis:
        image: redis
    server:
        restart: always
        build: 
            context: './server'
        ports: 
            - 80:80
        depends_on:
            - api
            - client
    api:
        build: 
            dockerfile: 'Dockerfile.dev'
            context: './api/'
        volumes: 
            - /app/node_modules
            - ./api:/app
        environment: 
            REDIS_HOST: 'redis'
            REDIS_PORT: '6379'
            PG_USER: 'postgres'
            PG_HOST: 'postgres'
            PG_DATABASE: 'postgres'
            PG_PASSWORD: 'root12345'
            PG_PORT: '5432'
            PORT: '3000'
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            REDIS_HOST: 'redis'
            REDIS_PORT: '6379'
